# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2340, 1476)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_hand_eye_2 = QtWidgets.QWidget()
        self.page_hand_eye_2.setObjectName("page_hand_eye_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_hand_eye_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.page_hand_eye_2)
        self.tabWidget_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_17 = QtWidgets.QLabel(self.tab_9)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_35.addWidget(self.label_17)
        self.IR_hololens_conn = QtWidgets.QPushButton(self.tab_9)
        self.IR_hololens_conn.setObjectName("IR_hololens_conn")
        self.horizontalLayout_35.addWidget(self.IR_hololens_conn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_8 = QtWidgets.QLabel(self.tab_9)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_28.addWidget(self.label_8)
        self.CollectStartButton = QtWidgets.QPushButton(self.tab_9)
        self.CollectStartButton.setObjectName("CollectStartButton")
        self.horizontalLayout_28.addWidget(self.CollectStartButton)
        self.VideoNameLineEdit = QtWidgets.QLineEdit(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoNameLineEdit.sizePolicy().hasHeightForWidth())
        self.VideoNameLineEdit.setSizePolicy(sizePolicy)
        self.VideoNameLineEdit.setObjectName("VideoNameLineEdit")
        self.horizontalLayout_28.addWidget(self.VideoNameLineEdit)
        self.CollectFrameSpinBox = QtWidgets.QSpinBox(self.tab_9)
        self.CollectFrameSpinBox.setMaximum(1000)
        self.CollectFrameSpinBox.setProperty("value", 300)
        self.CollectFrameSpinBox.setObjectName("CollectFrameSpinBox")
        self.horizontalLayout_28.addWidget(self.CollectFrameSpinBox)
        self.label_10 = QtWidgets.QLabel(self.tab_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_28.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_13 = QtWidgets.QLabel(self.tab_9)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_30.addWidget(self.label_13)
        self.ProvideStartButton = QtWidgets.QPushButton(self.tab_9)
        self.ProvideStartButton.setObjectName("ProvideStartButton")
        self.horizontalLayout_30.addWidget(self.ProvideStartButton)
        self.CollectProgressorbar = QtWidgets.QProgressBar(self.tab_9)
        self.CollectProgressorbar.setProperty("value", 0)
        self.CollectProgressorbar.setObjectName("CollectProgressorbar")
        self.horizontalLayout_30.addWidget(self.CollectProgressorbar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_14 = QtWidgets.QLabel(self.tab_9)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_33.addWidget(self.label_14)
        self.ToolDefFileNameEditLine = QtWidgets.QLineEdit(self.tab_9)
        self.ToolDefFileNameEditLine.setObjectName("ToolDefFileNameEditLine")
        self.horizontalLayout_33.addWidget(self.ToolDefFileNameEditLine)
        self.ToolConstructionTool = QtWidgets.QPushButton(self.tab_9)
        self.ToolConstructionTool.setObjectName("ToolConstructionTool")
        self.horizontalLayout_33.addWidget(self.ToolConstructionTool)
        self.ToolDefNameEditLine = QtWidgets.QLineEdit(self.tab_9)
        self.ToolDefNameEditLine.setObjectName("ToolDefNameEditLine")
        self.horizontalLayout_33.addWidget(self.ToolDefNameEditLine)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_23 = QtWidgets.QLabel(self.tab_9)
        self.label_23.setMinimumSize(QtCore.QSize(100, 0))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_46.addWidget(self.label_23)
        self.AHATExperimentTrackingButton = QtWidgets.QPushButton(self.tab_9)
        self.AHATExperimentTrackingButton.setObjectName("AHATExperimentTrackingButton")
        self.horizontalLayout_46.addWidget(self.AHATExperimentTrackingButton)
        self.KalmanCheckBox = QtWidgets.QCheckBox(self.tab_9)
        self.KalmanCheckBox.setObjectName("KalmanCheckBox")
        self.horizontalLayout_46.addWidget(self.KalmanCheckBox)
        self.IGTDisplayCheckBox = QtWidgets.QCheckBox(self.tab_9)
        self.IGTDisplayCheckBox.setObjectName("IGTDisplayCheckBox")
        self.horizontalLayout_46.addWidget(self.IGTDisplayCheckBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_46)
        self.groupBox = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.AHAT_acq = QtWidgets.QCheckBox(self.groupBox)
        self.AHAT_acq.setObjectName("AHAT_acq")
        self.horizontalLayout_7.addWidget(self.AHAT_acq)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.fps_AHAT = QtWidgets.QLabel(self.groupBox)
        self.fps_AHAT.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_AHAT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_AHAT.setObjectName("fps_AHAT")
        self.horizontalLayout_7.addWidget(self.fps_AHAT)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.LF_acq = QtWidgets.QCheckBox(self.groupBox)
        self.LF_acq.setEnabled(True)
        self.LF_acq.setObjectName("LF_acq")
        self.horizontalLayout_13.addWidget(self.LF_acq)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.fps_LF = QtWidgets.QLabel(self.groupBox)
        self.fps_LF.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_LF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_LF.setObjectName("fps_LF")
        self.horizontalLayout_13.addWidget(self.fps_LF)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.RF_acq = QtWidgets.QCheckBox(self.groupBox)
        self.RF_acq.setObjectName("RF_acq")
        self.horizontalLayout_14.addWidget(self.RF_acq)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.fps_RF = QtWidgets.QLabel(self.groupBox)
        self.fps_RF.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_RF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_RF.setObjectName("fps_RF")
        self.horizontalLayout_14.addWidget(self.fps_RF)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.LL_acq = QtWidgets.QCheckBox(self.groupBox)
        self.LL_acq.setObjectName("LL_acq")
        self.horizontalLayout_19.addWidget(self.LL_acq)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.fps_LL = QtWidgets.QLabel(self.groupBox)
        self.fps_LL.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_LL.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.fps_LL.setObjectName("fps_LL")
        self.horizontalLayout_19.addWidget(self.fps_LL)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.RR_acq = QtWidgets.QCheckBox(self.groupBox)
        self.RR_acq.setObjectName("RR_acq")
        self.horizontalLayout_20.addWidget(self.RR_acq)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.fps_RR = QtWidgets.QLabel(self.groupBox)
        self.fps_RR.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_RR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_RR.setObjectName("fps_RR")
        self.horizontalLayout_20.addWidget(self.fps_RR)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.down_limit = QtWidgets.QSlider(self.groupBox_3)
        self.down_limit.setMaximum(1024)
        self.down_limit.setProperty("value", 128)
        self.down_limit.setOrientation(QtCore.Qt.Horizontal)
        self.down_limit.setObjectName("down_limit")
        self.horizontalLayout_4.addWidget(self.down_limit)
        self.Down_limit_value = QtWidgets.QLabel(self.groupBox_3)
        self.Down_limit_value.setMinimumSize(QtCore.QSize(50, 30))
        self.Down_limit_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Down_limit_value.setObjectName("Down_limit_value")
        self.horizontalLayout_4.addWidget(self.Down_limit_value)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.up_limit = QtWidgets.QSlider(self.groupBox_3)
        self.up_limit.setMaximum(1024)
        self.up_limit.setProperty("value", 512)
        self.up_limit.setOrientation(QtCore.Qt.Horizontal)
        self.up_limit.setObjectName("up_limit")
        self.horizontalLayout_12.addWidget(self.up_limit)
        self.Up_limit_value = QtWidgets.QLabel(self.groupBox_3)
        self.Up_limit_value.setMinimumSize(QtCore.QSize(50, 30))
        self.Up_limit_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Up_limit_value.setObjectName("Up_limit_value")
        self.horizontalLayout_12.addWidget(self.Up_limit_value)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_18.addLayout(self.verticalLayout_11)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget_4.addTab(self.tab_9, "")
        self.verticalLayout_5.addWidget(self.tabWidget_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.page_hand_eye_2)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Depth_image = QtWidgets.QLabel(self.tab_8)
        self.Depth_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Depth_image.sizePolicy().hasHeightForWidth())
        self.Depth_image.setSizePolicy(sizePolicy)
        self.Depth_image.setMinimumSize(QtCore.QSize(512, 512))
        self.Depth_image.setFrameShape(QtWidgets.QFrame.Box)
        self.Depth_image.setLineWidth(2)
        self.Depth_image.setAlignment(QtCore.Qt.AlignCenter)
        self.Depth_image.setObjectName("Depth_image")
        self.verticalLayout_9.addWidget(self.Depth_image)
        self.Ab_image = QtWidgets.QLabel(self.tab_8)
        self.Ab_image.setMinimumSize(QtCore.QSize(512, 512))
        self.Ab_image.setFrameShape(QtWidgets.QFrame.Box)
        self.Ab_image.setLineWidth(2)
        self.Ab_image.setAlignment(QtCore.Qt.AlignCenter)
        self.Ab_image.setObjectName("Ab_image")
        self.verticalLayout_9.addWidget(self.Ab_image)
        self.horizontalLayout_16.addLayout(self.verticalLayout_9)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.LFImage = QtWidgets.QLabel(self.tab_8)
        self.LFImage.setMinimumSize(QtCore.QSize(480, 640))
        self.LFImage.setMaximumSize(QtCore.QSize(480, 640))
        self.LFImage.setFrameShape(QtWidgets.QFrame.Box)
        self.LFImage.setLineWidth(2)
        self.LFImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LFImage.setObjectName("LFImage")
        self.verticalLayout_12.addWidget(self.LFImage)
        self.LLImage = QtWidgets.QLabel(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LLImage.sizePolicy().hasHeightForWidth())
        self.LLImage.setSizePolicy(sizePolicy)
        self.LLImage.setMinimumSize(QtCore.QSize(480, 640))
        self.LLImage.setMaximumSize(QtCore.QSize(480, 640))
        self.LLImage.setFrameShape(QtWidgets.QFrame.Box)
        self.LLImage.setLineWidth(2)
        self.LLImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LLImage.setObjectName("LLImage")
        self.verticalLayout_12.addWidget(self.LLImage)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.RFImage = QtWidgets.QLabel(self.tab_8)
        self.RFImage.setMinimumSize(QtCore.QSize(480, 640))
        self.RFImage.setMaximumSize(QtCore.QSize(480, 640))
        self.RFImage.setFrameShape(QtWidgets.QFrame.Box)
        self.RFImage.setLineWidth(2)
        self.RFImage.setAlignment(QtCore.Qt.AlignCenter)
        self.RFImage.setObjectName("RFImage")
        self.verticalLayout_13.addWidget(self.RFImage)
        self.RRImage = QtWidgets.QLabel(self.tab_8)
        self.RRImage.setMinimumSize(QtCore.QSize(480, 640))
        self.RRImage.setMaximumSize(QtCore.QSize(480, 640))
        self.RRImage.setFrameShape(QtWidgets.QFrame.Box)
        self.RRImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RRImage.setLineWidth(2)
        self.RRImage.setAlignment(QtCore.Qt.AlignCenter)
        self.RRImage.setObjectName("RRImage")
        self.verticalLayout_13.addWidget(self.RRImage)
        self.horizontalLayout_16.addLayout(self.verticalLayout_13)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_16)
        self.tabWidget_5.addTab(self.tab_8, "")
        self.horizontalLayout_11.addWidget(self.tabWidget_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.stackedWidget_2.addWidget(self.page_hand_eye_2)
        self.page_IR_2 = QtWidgets.QWidget()
        self.page_IR_2.setObjectName("page_IR_2")
        self.stackedWidget_2.addWidget(self.page_IR_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2340, 22))
        self.menubar.setObjectName("menubar")
        self.menuVR_registratoin = QtWidgets.QMenu(self.menubar)
        self.menuVR_registratoin.setObjectName("menuVR_registratoin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHand_eye_calibration = QtWidgets.QAction(MainWindow)
        self.actionHand_eye_calibration.setObjectName("actionHand_eye_calibration")
        self.actionIR_Image_research_mode = QtWidgets.QAction(MainWindow)
        self.actionIR_Image_research_mode.setObjectName("actionIR_Image_research_mode")
        self.actionIR_marker_tracing = QtWidgets.QAction(MainWindow)
        self.actionIR_marker_tracing.setObjectName("actionIR_marker_tracing")
        self.menuVR_registratoin.addAction(self.actionHand_eye_calibration)
        self.menuVR_registratoin.addAction(self.actionIR_marker_tracing)
        self.menubar.addAction(self.menuVR_registratoin.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.ProvideStartButton.clicked.connect(MainWindow.TestSensorDataPerfusion)
        self.RR_acq.stateChanged['int'].connect(MainWindow.RR_Display)
        self.IR_hololens_conn.clicked.connect(MainWindow.IR_hololens_connect)
        self.down_limit.valueChanged['int'].connect(MainWindow.Down_limit_change)
        self.AHAT_acq.stateChanged['int'].connect(MainWindow.AHAT_Display)
        self.RF_acq.stateChanged['int'].connect(MainWindow.RF_Display)
        self.KalmanCheckBox.clicked['bool'].connect(MainWindow.KalmanFIlterCheckBoxClicked)
        self.CollectStartButton.clicked.connect(MainWindow.CollectSensorTestData)
        self.LF_acq.stateChanged['int'].connect(MainWindow.LF_Display)
        self.ToolConstructionTool.clicked.connect(MainWindow.OnToolConstructionButtonClicked)
        self.up_limit.valueChanged['int'].connect(MainWindow.Up_limit_change)
        self.LL_acq.stateChanged['int'].connect(MainWindow.LL_Display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Connection"))
        self.IR_hololens_conn.setText(_translate("MainWindow", "Connect to Hololens View"))
        self.label_8.setText(_translate("MainWindow", "Offline Data  "))
        self.CollectStartButton.setText(_translate("MainWindow", "Collect"))
        self.VideoNameLineEdit.setText(_translate("MainWindow", "OfflineVideoName"))
        self.label_10.setText(_translate("MainWindow", "frames"))
        self.ProvideStartButton.setText(_translate("MainWindow", "Provide"))
        self.label_14.setText(_translate("MainWindow", "Tool Def"))
        self.ToolDefFileNameEditLine.setText(_translate("MainWindow", "OfflineVideoName"))
        self.ToolConstructionTool.setText(_translate("MainWindow", "ConstructTool"))
        self.ToolDefNameEditLine.setText(_translate("MainWindow", "ToolName"))
        self.label_23.setText(_translate("MainWindow", "Tool Track"))
        self.AHATExperimentTrackingButton.setText(_translate("MainWindow", "Track"))
        self.KalmanCheckBox.setText(_translate("MainWindow", "Kalman Filter"))
        self.IGTDisplayCheckBox.setText(_translate("MainWindow", "Slicer Display"))
        self.groupBox.setTitle(_translate("MainWindow", "Open Sensors"))
        self.AHAT_acq.setText(_translate("MainWindow", "AHAT"))
        self.fps_AHAT.setText(_translate("MainWindow", "fps"))
        self.LF_acq.setText(_translate("MainWindow", "Left Front"))
        self.fps_LF.setText(_translate("MainWindow", "fps"))
        self.RF_acq.setText(_translate("MainWindow", "Right Front"))
        self.fps_RF.setText(_translate("MainWindow", "fps"))
        self.LL_acq.setText(_translate("MainWindow", "Left Left"))
        self.fps_LL.setText(_translate("MainWindow", "fps"))
        self.RR_acq.setText(_translate("MainWindow", "Right Right"))
        self.fps_RR.setText(_translate("MainWindow", "fps"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reflectivity Display Parameters"))
        self.label_2.setText(_translate("MainWindow", "Down limit"))
        self.Down_limit_value.setText(_translate("MainWindow", "128"))
        self.label_5.setText(_translate("MainWindow", "Upper limit"))
        self.Up_limit_value.setText(_translate("MainWindow", "512"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("MainWindow", "Control Area"))
        self.Depth_image.setText(_translate("MainWindow", "Depth image"))
        self.Ab_image.setText(_translate("MainWindow", "Ab image"))
        self.LFImage.setText(_translate("MainWindow", "Left Front"))
        self.LLImage.setText(_translate("MainWindow", "Left Left"))
        self.RFImage.setText(_translate("MainWindow", "Right Front"))
        self.RRImage.setText(_translate("MainWindow", "Right RIght"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_8), _translate("MainWindow", "Sensor Image Display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sensor Data"))
        self.menuVR_registratoin.setTitle(_translate("MainWindow", "VR registratoin"))
        self.actionHand_eye_calibration.setText(_translate("MainWindow", "Hand eye calibration"))
        self.actionIR_Image_research_mode.setText(_translate("MainWindow", "IR Image research mode"))
        self.actionIR_marker_tracing.setText(_translate("MainWindow", "IR marker tracing"))
