# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2340, 1476)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_hand_eye_2 = QtWidgets.QWidget()
        self.page_hand_eye_2.setObjectName("page_hand_eye_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_hand_eye_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.IR_hololens_conn = QtWidgets.QPushButton(self.page_hand_eye_2)
        self.IR_hololens_conn.setObjectName("IR_hololens_conn")
        self.verticalLayout_4.addWidget(self.IR_hololens_conn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_hand_eye_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.down_limit = QtWidgets.QSlider(self.groupBox_3)
        self.down_limit.setMaximum(1024)
        self.down_limit.setProperty("value", 128)
        self.down_limit.setOrientation(QtCore.Qt.Horizontal)
        self.down_limit.setObjectName("down_limit")
        self.horizontalLayout_4.addWidget(self.down_limit)
        self.Down_limit_value = QtWidgets.QLabel(self.groupBox_3)
        self.Down_limit_value.setMinimumSize(QtCore.QSize(50, 30))
        self.Down_limit_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Down_limit_value.setObjectName("Down_limit_value")
        self.horizontalLayout_4.addWidget(self.Down_limit_value)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.up_limit = QtWidgets.QSlider(self.groupBox_3)
        self.up_limit.setMaximum(1024)
        self.up_limit.setProperty("value", 512)
        self.up_limit.setOrientation(QtCore.Qt.Horizontal)
        self.up_limit.setObjectName("up_limit")
        self.horizontalLayout_12.addWidget(self.up_limit)
        self.Up_limit_value = QtWidgets.QLabel(self.groupBox_3)
        self.Up_limit_value.setMinimumSize(QtCore.QSize(50, 30))
        self.Up_limit_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Up_limit_value.setObjectName("Up_limit_value")
        self.horizontalLayout_12.addWidget(self.Up_limit_value)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_18.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.page_hand_eye_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.AHAT_acq = QtWidgets.QCheckBox(self.groupBox)
        self.AHAT_acq.setObjectName("AHAT_acq")
        self.horizontalLayout_7.addWidget(self.AHAT_acq)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.fps_AHAT = QtWidgets.QLabel(self.groupBox)
        self.fps_AHAT.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_AHAT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_AHAT.setObjectName("fps_AHAT")
        self.horizontalLayout_7.addWidget(self.fps_AHAT)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.LF_acq = QtWidgets.QCheckBox(self.groupBox)
        self.LF_acq.setEnabled(True)
        self.LF_acq.setObjectName("LF_acq")
        self.horizontalLayout_13.addWidget(self.LF_acq)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.fps_LF = QtWidgets.QLabel(self.groupBox)
        self.fps_LF.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_LF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_LF.setObjectName("fps_LF")
        self.horizontalLayout_13.addWidget(self.fps_LF)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.RF_acq = QtWidgets.QCheckBox(self.groupBox)
        self.RF_acq.setObjectName("RF_acq")
        self.horizontalLayout_14.addWidget(self.RF_acq)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.fps_RF = QtWidgets.QLabel(self.groupBox)
        self.fps_RF.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_RF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_RF.setObjectName("fps_RF")
        self.horizontalLayout_14.addWidget(self.fps_RF)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.LL_acq = QtWidgets.QCheckBox(self.groupBox)
        self.LL_acq.setObjectName("LL_acq")
        self.horizontalLayout_19.addWidget(self.LL_acq)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.fps_LL = QtWidgets.QLabel(self.groupBox)
        self.fps_LL.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_LL.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.fps_LL.setObjectName("fps_LL")
        self.horizontalLayout_19.addWidget(self.fps_LL)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.RR_acq = QtWidgets.QCheckBox(self.groupBox)
        self.RR_acq.setObjectName("RR_acq")
        self.horizontalLayout_20.addWidget(self.RR_acq)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.fps_RR = QtWidgets.QLabel(self.groupBox)
        self.fps_RR.setMinimumSize(QtCore.QSize(50, 0))
        self.fps_RR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_RR.setObjectName("fps_RR")
        self.horizontalLayout_20.addWidget(self.fps_RR)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.page_hand_eye_2)
        self.tabWidget_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_8 = QtWidgets.QLabel(self.tab_9)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_28.addWidget(self.label_8)
        self.CollectStartButton = QtWidgets.QPushButton(self.tab_9)
        self.CollectStartButton.setObjectName("CollectStartButton")
        self.horizontalLayout_28.addWidget(self.CollectStartButton)
        self.VideoNameLineEdit = QtWidgets.QLineEdit(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoNameLineEdit.sizePolicy().hasHeightForWidth())
        self.VideoNameLineEdit.setSizePolicy(sizePolicy)
        self.VideoNameLineEdit.setObjectName("VideoNameLineEdit")
        self.horizontalLayout_28.addWidget(self.VideoNameLineEdit)
        self.CollectFrameSpinBox = QtWidgets.QSpinBox(self.tab_9)
        self.CollectFrameSpinBox.setMaximum(1000)
        self.CollectFrameSpinBox.setProperty("value", 180)
        self.CollectFrameSpinBox.setObjectName("CollectFrameSpinBox")
        self.horizontalLayout_28.addWidget(self.CollectFrameSpinBox)
        self.label_10 = QtWidgets.QLabel(self.tab_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_28.addWidget(self.label_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_13 = QtWidgets.QLabel(self.tab_9)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_30.addWidget(self.label_13)
        self.ProvideStartButton = QtWidgets.QPushButton(self.tab_9)
        self.ProvideStartButton.setObjectName("ProvideStartButton")
        self.horizontalLayout_30.addWidget(self.ProvideStartButton)
        self.CollectProgressorbar = QtWidgets.QProgressBar(self.tab_9)
        self.CollectProgressorbar.setProperty("value", 0)
        self.CollectProgressorbar.setObjectName("CollectProgressorbar")
        self.horizontalLayout_30.addWidget(self.CollectProgressorbar)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.tab_9)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.KalmanCheckBox = QtWidgets.QCheckBox(self.tab_9)
        self.KalmanCheckBox.setObjectName("KalmanCheckBox")
        self.horizontalLayout_8.addWidget(self.KalmanCheckBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_17 = QtWidgets.QLabel(self.tab_9)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_35.addWidget(self.label_17)
        self.HololenUnityDisplayConnection = QtWidgets.QPushButton(self.tab_9)
        self.HololenUnityDisplayConnection.setObjectName("HololenUnityDisplayConnection")
        self.horizontalLayout_35.addWidget(self.HololenUnityDisplayConnection)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_35)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_14 = QtWidgets.QLabel(self.tab_10)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_32.addWidget(self.label_14)
        self.ToolDefPreviewButton = QtWidgets.QPushButton(self.tab_10)
        self.ToolDefPreviewButton.setObjectName("ToolDefPreviewButton")
        self.horizontalLayout_32.addWidget(self.ToolDefPreviewButton)
        self.ToolDefCollectButton = QtWidgets.QPushButton(self.tab_10)
        self.ToolDefCollectButton.setObjectName("ToolDefCollectButton")
        self.horizontalLayout_32.addWidget(self.ToolDefCollectButton)
        self.ToolDefFrameSpinBox = QtWidgets.QSpinBox(self.tab_10)
        self.ToolDefFrameSpinBox.setMinimum(10)
        self.ToolDefFrameSpinBox.setMaximum(997)
        self.ToolDefFrameSpinBox.setProperty("value", 300)
        self.ToolDefFrameSpinBox.setObjectName("ToolDefFrameSpinBox")
        self.horizontalLayout_32.addWidget(self.ToolDefFrameSpinBox)
        self.label_15 = QtWidgets.QLabel(self.tab_10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_32.addWidget(self.label_15)
        self.ToolDefprogressBar = QtWidgets.QProgressBar(self.tab_10)
        self.ToolDefprogressBar.setProperty("value", 0)
        self.ToolDefprogressBar.setObjectName("ToolDefprogressBar")
        self.horizontalLayout_32.addWidget(self.ToolDefprogressBar)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem11)
        self.verticalLayout_21.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_16 = QtWidgets.QLabel(self.tab_10)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_33.addWidget(self.label_16)
        self.ToolDefFileNameEditLine = QtWidgets.QLineEdit(self.tab_10)
        self.ToolDefFileNameEditLine.setObjectName("ToolDefFileNameEditLine")
        self.horizontalLayout_33.addWidget(self.ToolDefFileNameEditLine)
        self.ToolConstructionTool = QtWidgets.QPushButton(self.tab_10)
        self.ToolConstructionTool.setObjectName("ToolConstructionTool")
        self.horizontalLayout_33.addWidget(self.ToolConstructionTool)
        self.ToolDefNameEditLine = QtWidgets.QLineEdit(self.tab_10)
        self.ToolDefNameEditLine.setObjectName("ToolDefNameEditLine")
        self.horizontalLayout_33.addWidget(self.ToolDefNameEditLine)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem12)
        self.verticalLayout_21.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_23 = QtWidgets.QLabel(self.tab_10)
        self.label_23.setMinimumSize(QtCore.QSize(100, 0))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_46.addWidget(self.label_23)
        self.AHATExperimentCalibrationButton = QtWidgets.QPushButton(self.tab_10)
        self.AHATExperimentCalibrationButton.setObjectName("AHATExperimentCalibrationButton")
        self.horizontalLayout_46.addWidget(self.AHATExperimentCalibrationButton)
        self.AHATExperimentTrackingButton = QtWidgets.QPushButton(self.tab_10)
        self.AHATExperimentTrackingButton.setObjectName("AHATExperimentTrackingButton")
        self.horizontalLayout_46.addWidget(self.AHATExperimentTrackingButton)
        self.AHATExperimentTrackingObjectSelectionBox = QtWidgets.QComboBox(self.tab_10)
        self.AHATExperimentTrackingObjectSelectionBox.setObjectName("AHATExperimentTrackingObjectSelectionBox")
        self.horizontalLayout_46.addWidget(self.AHATExperimentTrackingObjectSelectionBox)
        self.AHATExperimentClearViewButton = QtWidgets.QPushButton(self.tab_10)
        self.AHATExperimentClearViewButton.setObjectName("AHATExperimentClearViewButton")
        self.horizontalLayout_46.addWidget(self.AHATExperimentClearViewButton)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem13)
        self.verticalLayout_21.addLayout(self.horizontalLayout_46)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem14)
        self.verticalLayout_23.addLayout(self.verticalLayout_21)
        self.tabWidget_4.addTab(self.tab_10, "")
        self.verticalLayout_5.addWidget(self.tabWidget_4)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.page_hand_eye_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_18 = QtWidgets.QLabel(self.tab_13)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_36.addWidget(self.label_18)
        self.RegisterXSlider = QtWidgets.QSlider(self.tab_13)
        self.RegisterXSlider.setMinimum(-2000)
        self.RegisterXSlider.setMaximum(2000)
        self.RegisterXSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RegisterXSlider.setObjectName("RegisterXSlider")
        self.horizontalLayout_36.addWidget(self.RegisterXSlider)
        self.LabelRegisterXDisplay = QtWidgets.QLabel(self.tab_13)
        self.LabelRegisterXDisplay.setMinimumSize(QtCore.QSize(50, 0))
        self.LabelRegisterXDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRegisterXDisplay.setObjectName("LabelRegisterXDisplay")
        self.horizontalLayout_36.addWidget(self.LabelRegisterXDisplay)
        self.verticalLayout_24.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_20 = QtWidgets.QLabel(self.tab_13)
        self.label_20.setMinimumSize(QtCore.QSize(50, 0))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_37.addWidget(self.label_20)
        self.RegisterYSlider = QtWidgets.QSlider(self.tab_13)
        self.RegisterYSlider.setMinimum(-2000)
        self.RegisterYSlider.setMaximum(2000)
        self.RegisterYSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RegisterYSlider.setObjectName("RegisterYSlider")
        self.horizontalLayout_37.addWidget(self.RegisterYSlider)
        self.LabelRegisterYDisplay = QtWidgets.QLabel(self.tab_13)
        self.LabelRegisterYDisplay.setMinimumSize(QtCore.QSize(50, 0))
        self.LabelRegisterYDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRegisterYDisplay.setObjectName("LabelRegisterYDisplay")
        self.horizontalLayout_37.addWidget(self.LabelRegisterYDisplay)
        self.verticalLayout_24.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_22 = QtWidgets.QLabel(self.tab_13)
        self.label_22.setMinimumSize(QtCore.QSize(50, 0))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_38.addWidget(self.label_22)
        self.RegisterZSlider = QtWidgets.QSlider(self.tab_13)
        self.RegisterZSlider.setMinimum(-2000)
        self.RegisterZSlider.setMaximum(2000)
        self.RegisterZSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RegisterZSlider.setObjectName("RegisterZSlider")
        self.horizontalLayout_38.addWidget(self.RegisterZSlider)
        self.LabelRegisterZDisplay = QtWidgets.QLabel(self.tab_13)
        self.LabelRegisterZDisplay.setMinimumSize(QtCore.QSize(50, 0))
        self.LabelRegisterZDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRegisterZDisplay.setObjectName("LabelRegisterZDisplay")
        self.horizontalLayout_38.addWidget(self.LabelRegisterZDisplay)
        self.verticalLayout_24.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_24 = QtWidgets.QLabel(self.tab_13)
        self.label_24.setMinimumSize(QtCore.QSize(50, 0))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_47.addWidget(self.label_24)
        self.RegisterXangleSlider = QtWidgets.QSlider(self.tab_13)
        self.RegisterXangleSlider.setMinimum(-10000)
        self.RegisterXangleSlider.setMaximum(10000)
        self.RegisterXangleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RegisterXangleSlider.setObjectName("RegisterXangleSlider")
        self.horizontalLayout_47.addWidget(self.RegisterXangleSlider)
        self.LabelRegisterXAngleDisplay = QtWidgets.QLabel(self.tab_13)
        self.LabelRegisterXAngleDisplay.setMinimumSize(QtCore.QSize(50, 0))
        self.LabelRegisterXAngleDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRegisterXAngleDisplay.setObjectName("LabelRegisterXAngleDisplay")
        self.horizontalLayout_47.addWidget(self.LabelRegisterXAngleDisplay)
        self.verticalLayout_24.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_26 = QtWidgets.QLabel(self.tab_13)
        self.label_26.setMinimumSize(QtCore.QSize(50, 0))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_48.addWidget(self.label_26)
        self.RegisterYangleSlider = QtWidgets.QSlider(self.tab_13)
        self.RegisterYangleSlider.setMinimum(-10000)
        self.RegisterYangleSlider.setMaximum(10000)
        self.RegisterYangleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RegisterYangleSlider.setObjectName("RegisterYangleSlider")
        self.horizontalLayout_48.addWidget(self.RegisterYangleSlider)
        self.LabelRegisterYAngleDisplay = QtWidgets.QLabel(self.tab_13)
        self.LabelRegisterYAngleDisplay.setMinimumSize(QtCore.QSize(50, 0))
        self.LabelRegisterYAngleDisplay.setToolTipDuration(7)
        self.LabelRegisterYAngleDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRegisterYAngleDisplay.setObjectName("LabelRegisterYAngleDisplay")
        self.horizontalLayout_48.addWidget(self.LabelRegisterYAngleDisplay)
        self.verticalLayout_24.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_28 = QtWidgets.QLabel(self.tab_13)
        self.label_28.setMinimumSize(QtCore.QSize(50, 0))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_49.addWidget(self.label_28)
        self.RegisterZangleSlider = QtWidgets.QSlider(self.tab_13)
        self.RegisterZangleSlider.setMinimum(-10000)
        self.RegisterZangleSlider.setMaximum(10000)
        self.RegisterZangleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RegisterZangleSlider.setObjectName("RegisterZangleSlider")
        self.horizontalLayout_49.addWidget(self.RegisterZangleSlider)
        self.LabelRegisterZAngleDisplay = QtWidgets.QLabel(self.tab_13)
        self.LabelRegisterZAngleDisplay.setMinimumSize(QtCore.QSize(50, 0))
        self.LabelRegisterZAngleDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRegisterZAngleDisplay.setObjectName("LabelRegisterZAngleDisplay")
        self.horizontalLayout_49.addWidget(self.LabelRegisterZAngleDisplay)
        self.verticalLayout_24.addLayout(self.horizontalLayout_49)
        self.RegisterResultSavingButton = QtWidgets.QPushButton(self.tab_13)
        self.RegisterResultSavingButton.setObjectName("RegisterResultSavingButton")
        self.verticalLayout_24.addWidget(self.RegisterResultSavingButton)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_19 = QtWidgets.QLabel(self.tab_13)
        self.label_19.setMinimumSize(QtCore.QSize(50, 0))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_39.addWidget(self.label_19)
        self.UnityDelaySettingSlider = QtWidgets.QSlider(self.tab_13)
        self.UnityDelaySettingSlider.setMaximum(60)
        self.UnityDelaySettingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.UnityDelaySettingSlider.setObjectName("UnityDelaySettingSlider")
        self.horizontalLayout_39.addWidget(self.UnityDelaySettingSlider)
        self.UnityDelayDisplayLabel = QtWidgets.QLabel(self.tab_13)
        self.UnityDelayDisplayLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.UnityDelayDisplayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UnityDelayDisplayLabel.setObjectName("UnityDelayDisplayLabel")
        self.horizontalLayout_39.addWidget(self.UnityDelayDisplayLabel)
        self.verticalLayout_24.addLayout(self.horizontalLayout_39)
        self.UnityDelaySettingButton = QtWidgets.QPushButton(self.tab_13)
        self.UnityDelaySettingButton.setObjectName("UnityDelaySettingButton")
        self.verticalLayout_24.addWidget(self.UnityDelaySettingButton)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.unityslerpsettingbutton = QtWidgets.QPushButton(self.tab_13)
        self.unityslerpsettingbutton.setMinimumSize(QtCore.QSize(100, 0))
        self.unityslerpsettingbutton.setObjectName("unityslerpsettingbutton")
        self.horizontalLayout_40.addWidget(self.unityslerpsettingbutton)
        self.unityslerpsettingslider = QtWidgets.QSlider(self.tab_13)
        self.unityslerpsettingslider.setMinimum(1)
        self.unityslerpsettingslider.setMaximum(100)
        self.unityslerpsettingslider.setProperty("value", 40)
        self.unityslerpsettingslider.setOrientation(QtCore.Qt.Horizontal)
        self.unityslerpsettingslider.setObjectName("unityslerpsettingslider")
        self.horizontalLayout_40.addWidget(self.unityslerpsettingslider)
        self.unityslerpvaluedisplaylabel = QtWidgets.QLabel(self.tab_13)
        self.unityslerpvaluedisplaylabel.setMinimumSize(QtCore.QSize(50, 0))
        self.unityslerpvaluedisplaylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.unityslerpvaluedisplaylabel.setObjectName("unityslerpvaluedisplaylabel")
        self.horizontalLayout_40.addWidget(self.unityslerpvaluedisplaylabel)
        self.verticalLayout_24.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.unityintersettingbutton = QtWidgets.QPushButton(self.tab_13)
        self.unityintersettingbutton.setMinimumSize(QtCore.QSize(100, 0))
        self.unityintersettingbutton.setObjectName("unityintersettingbutton")
        self.horizontalLayout_43.addWidget(self.unityintersettingbutton)
        self.unityintersettingslider = QtWidgets.QSlider(self.tab_13)
        self.unityintersettingslider.setMinimum(1)
        self.unityintersettingslider.setMaximum(100)
        self.unityintersettingslider.setProperty("value", 50)
        self.unityintersettingslider.setOrientation(QtCore.Qt.Horizontal)
        self.unityintersettingslider.setObjectName("unityintersettingslider")
        self.horizontalLayout_43.addWidget(self.unityintersettingslider)
        self.unityintervaluedisplaylabel = QtWidgets.QLabel(self.tab_13)
        self.unityintervaluedisplaylabel.setMinimumSize(QtCore.QSize(50, 0))
        self.unityintervaluedisplaylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.unityintervaluedisplaylabel.setObjectName("unityintervaluedisplaylabel")
        self.horizontalLayout_43.addWidget(self.unityintervaluedisplaylabel)
        self.verticalLayout_24.addLayout(self.horizontalLayout_43)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem15)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.tabWidget_3.addTab(self.tab_13, "")
        self.verticalLayout_5.addWidget(self.tabWidget_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem16)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.page_hand_eye_2)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Depth_image = QtWidgets.QLabel(self.tab_8)
        self.Depth_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Depth_image.sizePolicy().hasHeightForWidth())
        self.Depth_image.setSizePolicy(sizePolicy)
        self.Depth_image.setMinimumSize(QtCore.QSize(512, 512))
        self.Depth_image.setFrameShape(QtWidgets.QFrame.Box)
        self.Depth_image.setLineWidth(2)
        self.Depth_image.setAlignment(QtCore.Qt.AlignCenter)
        self.Depth_image.setObjectName("Depth_image")
        self.verticalLayout_9.addWidget(self.Depth_image)
        self.Ab_image = QtWidgets.QLabel(self.tab_8)
        self.Ab_image.setMinimumSize(QtCore.QSize(512, 512))
        self.Ab_image.setFrameShape(QtWidgets.QFrame.Box)
        self.Ab_image.setLineWidth(2)
        self.Ab_image.setAlignment(QtCore.Qt.AlignCenter)
        self.Ab_image.setObjectName("Ab_image")
        self.verticalLayout_9.addWidget(self.Ab_image)
        self.horizontalLayout_16.addLayout(self.verticalLayout_9)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.LFImage = QtWidgets.QLabel(self.tab_8)
        self.LFImage.setMinimumSize(QtCore.QSize(480, 640))
        self.LFImage.setMaximumSize(QtCore.QSize(480, 640))
        self.LFImage.setFrameShape(QtWidgets.QFrame.Box)
        self.LFImage.setLineWidth(2)
        self.LFImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LFImage.setObjectName("LFImage")
        self.verticalLayout_12.addWidget(self.LFImage)
        self.LLImage = QtWidgets.QLabel(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LLImage.sizePolicy().hasHeightForWidth())
        self.LLImage.setSizePolicy(sizePolicy)
        self.LLImage.setMinimumSize(QtCore.QSize(480, 640))
        self.LLImage.setMaximumSize(QtCore.QSize(480, 640))
        self.LLImage.setFrameShape(QtWidgets.QFrame.Box)
        self.LLImage.setLineWidth(2)
        self.LLImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LLImage.setObjectName("LLImage")
        self.verticalLayout_12.addWidget(self.LLImage)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.RFImage = QtWidgets.QLabel(self.tab_8)
        self.RFImage.setMinimumSize(QtCore.QSize(480, 640))
        self.RFImage.setMaximumSize(QtCore.QSize(480, 640))
        self.RFImage.setFrameShape(QtWidgets.QFrame.Box)
        self.RFImage.setLineWidth(2)
        self.RFImage.setAlignment(QtCore.Qt.AlignCenter)
        self.RFImage.setObjectName("RFImage")
        self.verticalLayout_13.addWidget(self.RFImage)
        self.RRImage = QtWidgets.QLabel(self.tab_8)
        self.RRImage.setMinimumSize(QtCore.QSize(480, 640))
        self.RRImage.setMaximumSize(QtCore.QSize(480, 640))
        self.RRImage.setFrameShape(QtWidgets.QFrame.Box)
        self.RRImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RRImage.setLineWidth(2)
        self.RRImage.setAlignment(QtCore.Qt.AlignCenter)
        self.RRImage.setObjectName("RRImage")
        self.verticalLayout_13.addWidget(self.RRImage)
        self.horizontalLayout_16.addLayout(self.verticalLayout_13)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_16)
        self.tabWidget_5.addTab(self.tab_8, "")
        self.horizontalLayout_11.addWidget(self.tabWidget_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.stackedWidget_2.addWidget(self.page_hand_eye_2)
        self.page_IR_2 = QtWidgets.QWidget()
        self.page_IR_2.setObjectName("page_IR_2")
        self.stackedWidget_2.addWidget(self.page_IR_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2340, 22))
        self.menubar.setObjectName("menubar")
        self.menuVR_registratoin = QtWidgets.QMenu(self.menubar)
        self.menuVR_registratoin.setObjectName("menuVR_registratoin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHand_eye_calibration = QtWidgets.QAction(MainWindow)
        self.actionHand_eye_calibration.setObjectName("actionHand_eye_calibration")
        self.actionIR_Image_research_mode = QtWidgets.QAction(MainWindow)
        self.actionIR_Image_research_mode.setObjectName("actionIR_Image_research_mode")
        self.actionIR_marker_tracing = QtWidgets.QAction(MainWindow)
        self.actionIR_marker_tracing.setObjectName("actionIR_marker_tracing")
        self.menuVR_registratoin.addAction(self.actionHand_eye_calibration)
        self.menuVR_registratoin.addAction(self.actionIR_marker_tracing)
        self.menubar.addAction(self.menuVR_registratoin.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.CollectStartButton.clicked.connect(MainWindow.CollectSensorTestData)
        self.ToolConstructionTool.clicked.connect(MainWindow.OnToolConstructionButtonClicked)
        self.LL_acq.stateChanged['int'].connect(MainWindow.LL_Display)
        self.up_limit.valueChanged['int'].connect(MainWindow.Up_limit_change)
        self.KalmanCheckBox.clicked['bool'].connect(MainWindow.KalmanFIlterCheckBoxClicked)
        self.RF_acq.stateChanged['int'].connect(MainWindow.RF_Display)
        self.ToolDefPreviewButton.clicked.connect(MainWindow.OnToolPreviewButtonClicked)
        self.down_limit.valueChanged['int'].connect(MainWindow.Down_limit_change)
        self.IR_hololens_conn.clicked.connect(MainWindow.IR_hololens_connect)
        self.LF_acq.stateChanged['int'].connect(MainWindow.LF_Display)
        self.ProvideStartButton.clicked.connect(MainWindow.TestSensorDataPerfusion)
        self.ToolDefCollectButton.clicked.connect(MainWindow.OnToolDefCollectionButtonClicked)
        self.RR_acq.stateChanged['int'].connect(MainWindow.RR_Display)
        self.AHAT_acq.stateChanged['int'].connect(MainWindow.AHAT_Display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.IR_hololens_conn.setText(_translate("MainWindow", "Connect to Hololens"))
        self.groupBox_3.setTitle(_translate("MainWindow", "AHAT Reflectivity"))
        self.label_2.setText(_translate("MainWindow", "Down limit"))
        self.Down_limit_value.setText(_translate("MainWindow", "128"))
        self.label_5.setText(_translate("MainWindow", "Upper limit"))
        self.Up_limit_value.setText(_translate("MainWindow", "512"))
        self.groupBox.setTitle(_translate("MainWindow", "Data Acquisition"))
        self.AHAT_acq.setText(_translate("MainWindow", "AHAT"))
        self.fps_AHAT.setText(_translate("MainWindow", "fps"))
        self.LF_acq.setText(_translate("MainWindow", "Left Front"))
        self.fps_LF.setText(_translate("MainWindow", "fps"))
        self.RF_acq.setText(_translate("MainWindow", "Right Front"))
        self.fps_RF.setText(_translate("MainWindow", "fps"))
        self.LL_acq.setText(_translate("MainWindow", "Left Left"))
        self.fps_LL.setText(_translate("MainWindow", "fps"))
        self.RR_acq.setText(_translate("MainWindow", "Right Right"))
        self.fps_RR.setText(_translate("MainWindow", "fps"))
        self.label_8.setText(_translate("MainWindow", "Offline Data  "))
        self.CollectStartButton.setText(_translate("MainWindow", "Collect"))
        self.VideoNameLineEdit.setText(_translate("MainWindow", "Video"))
        self.label_10.setText(_translate("MainWindow", "frames"))
        self.ProvideStartButton.setText(_translate("MainWindow", "Provide"))
        self.label_4.setText(_translate("MainWindow", "Tool Tracking"))
        self.KalmanCheckBox.setText(_translate("MainWindow", "Kalman Filter"))
        self.label_17.setText(_translate("MainWindow", "3D View"))
        self.HololenUnityDisplayConnection.setText(_translate("MainWindow", "Connect"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("MainWindow", "Control Area"))
        self.label_14.setText(_translate("MainWindow", "Tool Def"))
        self.ToolDefPreviewButton.setText(_translate("MainWindow", "Preview"))
        self.ToolDefCollectButton.setText(_translate("MainWindow", "Collect"))
        self.label_15.setText(_translate("MainWindow", "Frames"))
        self.ToolDefFileNameEditLine.setText(_translate("MainWindow", "DefaultToolDefFIle"))
        self.ToolConstructionTool.setText(_translate("MainWindow", "ConstructTool"))
        self.ToolDefNameEditLine.setText(_translate("MainWindow", "ToolName"))
        self.label_23.setText(_translate("MainWindow", "Tool Track"))
        self.AHATExperimentCalibrationButton.setText(_translate("MainWindow", "Calibration"))
        self.AHATExperimentTrackingButton.setText(_translate("MainWindow", "Track"))
        self.AHATExperimentClearViewButton.setText(_translate("MainWindow", "Clear View"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "Tool"))
        self.label_18.setText(_translate("MainWindow", "x"))
        self.LabelRegisterXDisplay.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "y"))
        self.LabelRegisterYDisplay.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "z"))
        self.LabelRegisterZDisplay.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "ax"))
        self.LabelRegisterXAngleDisplay.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "ay"))
        self.LabelRegisterYAngleDisplay.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "az"))
        self.LabelRegisterZAngleDisplay.setText(_translate("MainWindow", "0"))
        self.RegisterResultSavingButton.setText(_translate("MainWindow", "Save Register Result"))
        self.label_19.setText(_translate("MainWindow", "delay"))
        self.UnityDelayDisplayLabel.setText(_translate("MainWindow", "0"))
        self.UnityDelaySettingButton.setText(_translate("MainWindow", "Set Unity Delay"))
        self.unityslerpsettingbutton.setText(_translate("MainWindow", "Set slerp"))
        self.unityslerpvaluedisplaylabel.setText(_translate("MainWindow", "0.4"))
        self.unityintersettingbutton.setText(_translate("MainWindow", "Set Inter"))
        self.unityintervaluedisplaylabel.setText(_translate("MainWindow", "0.5"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "Register"))
        self.Depth_image.setText(_translate("MainWindow", "Depth image"))
        self.Ab_image.setText(_translate("MainWindow", "Ab image"))
        self.LFImage.setText(_translate("MainWindow", "Left Front"))
        self.LLImage.setText(_translate("MainWindow", "Left Left"))
        self.RFImage.setText(_translate("MainWindow", "Right Front"))
        self.RRImage.setText(_translate("MainWindow", "Right RIght"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_8), _translate("MainWindow", "Sensor Image Display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sensor Data"))
        self.menuVR_registratoin.setTitle(_translate("MainWindow", "VR registratoin"))
        self.actionHand_eye_calibration.setText(_translate("MainWindow", "Hand eye calibration"))
        self.actionIR_Image_research_mode.setText(_translate("MainWindow", "IR Image research mode"))
        self.actionIR_marker_tracing.setText(_translate("MainWindow", "IR marker tracing"))
